
<div style=" padding: 40px; text-align: center; color: #8e44ad;text-shadow: 2px 2px 0px #f1c40f; ">
    <h1 style="font-family: 'Roboto', sans-serif;ext-align: center;  font-size: 72px; margin-top: 0; margin-bottom: 20px;">
    Numpy
    </h1>
</div>

<div style=" padding: 40px; text-align: center; color: #8e44ad;text-shadow: 2px 2px 0px #f1c40f; ">
    <h1 style="font-family: 'Roboto', sans-serif;ext-align: center;  font-size: 72px; margin-top: 0; margin-bottom: 20px;">
    Exercise 2
    </h1>
</div>

![SNOWFALL](ex1.png)


In [1]:
# import libraries
import numpy as np

In [7]:
# get integer from user
 
try:
    num_user = int(input('enter your chosen number : '))
    print(num_user)
except:
    print('there is a problem . check and try again!')


7


In [8]:
# create an array of random numbers
arr = np.random.randint(0,101 , size=num_user)
arr

array([34, 42, 19, 54, 32, 27, 44])

In [9]:
# find max number of the arry
_Max = arr.max()
# np.max(arr)
print(_Max)

54


In [10]:
# Condition check
if _Max > 70 :
    print('win')

else :
    print('Fail')

Fail


In [11]:
print('win') if _Max > 70 else print('fail')

fail


<h4 style="text-align:center;"> 🔎 Numpy Functions You  Needed For Data Science 🧮 </h4>

<hr>
<h5 style="text-align:center; color:red ; font-size: 20px;">  🟢 linspace 🟢 </h5>
<p style="text-align:center; font-size: 20px;">
🔸
این تابع، یک آرایه شامل تعدادی اعداد فلوت بین دو مقدار داده شده با فاصله مساوی ایجاد می‌کند 
🔸
</p>

<div style="text-align:left; font-size: 20px;">

np.linspace(start,end,num)

start: starting index

end: last index

num: number of samples to generate, default = 50.
</div>

In [17]:
lin_arr = np.linspace(0 , 10 , 5)
lin_arr

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

<hr>
<h5 style="text-align:center; color:red ; font-size: 20px;">  🟢 arange 🟢 </h5>
<p style="text-align:center; font-size: 20px;">
🔸
این تابع، یک آرایه شامل یک دنباله اعداد صحیح از یک مقدار شروع تا یک مقدار پایان با یک فاصله دلخواه ایجاد می‌کند
🔸
</p>

<div style="text-align:left; font-size: 20px;">

np.arange(start,stop,step)

step: Space between values.



</div>

In [21]:
arang_arr = np.arange(0,11,5)
arang_arr

array([ 0,  5, 10])

<hr>
<h5 style="text-align:center; color:red ; font-size: 20px;">  🟢 Array of zero & one 🟢 </h5>
<p style="text-align:center; font-size: 20px;">
🔸یک آرایه با ابعاد دلخواه و تمام المان‌های آن برابر با صفر یا یک را ایجاد می‌کند
🔸
</p>

<div style="text-align:left; font-size: 20px;">

np.zeros(shape,dtype)

np.ones(shape,dtype)


shape: shape of the resultant array.

dtype: desired data type of resultant array. ‘int’ or default ‘float’




</div>

In [23]:
zero_arr = np.zeros((2,3) , dtype='int')
zero_arr

array([[0, 0, 0],
       [0, 0, 0]])

In [30]:
one_arr = np.ones((3,2))
one_arr

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

<hr>
<h5 style="text-align:center; color:red ; font-size: 20px;">  🟢 Full 🟢 </h5>
<p style="text-align:center; font-size: 20px;">
🔸یک آرایه شامل مقادیری که در تمامی المان‌های آن تکرار می‌شوند و با ابعاد دلخواه، ایجاد می‌کند
🔸
</p>

<div style="text-align:left; font-size: 20px;">

np.full(shape , fill_value)

fill_value: Random value to fill inside the array

</div>

In [34]:
full_arr = np.full((4,4),fill_value=3 , dtype='float')
full_arr

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

<hr>
<h5 style="text-align:center; color:red ; font-size: 20px;">  🟢 Identity 🟢 </h5>
<p style="text-align:center; font-size: 20px;">
🔸
یک ماتریس واحد با ابعاد مشخص ایجاد می کند 
🔸
</p>

In [35]:
id_arr = np.identity(3)
id_arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

<hr>
<h5 style="text-align:center; color:red ; font-size: 20px;">  🟢 Min - Max - Mean - Median 🟢 </h5>
<p style="text-align:center; font-size: 20px;">

</p>

In [36]:
arr = np.array([1,1,2,3,3,4,5,6,6,2])

In [37]:
np.min(arr)
# arr.max()

1

In [38]:
np.max(arr)


6

In [40]:
np.mean(arr)

3.3

In [41]:
np.median(arr) 

3.0

In [43]:
np.unique(arr ,return_counts=True)

(array([1, 2, 3, 4, 5, 6]), array([2, 2, 2, 1, 1, 2]))

<hr>
<h5 style="text-align:center; color:red ; font-size: 20px;">  🟢 Reshape 🟢 </h5>
<p style="text-align:center; font-size: 20px;">
🔸
یکی از پرکاربردترین توابع  است. آرایه ای حاوی همان داده ها را با شکل جدید برمی گرداند🔸
</p>

In [44]:
A = np.random.randint(15,size=(4,3))
A

array([[12, 14,  3],
       [ 1, 10, 10],
       [ 9,  8,  0],
       [ 2,  2,  6]])

In [46]:
A.reshape(3,4)
# np.reshape(arr , (4,3))

array([[12, 14,  3,  1],
       [10, 10,  9,  8],
       [ 0,  2,  2,  6]])

In [47]:
A.reshape(-1)  
# np.reshape(arr , -1)

array([12, 14,  3,  1, 10, 10,  9,  8,  0,  2,  2,  6])

<hr>
<h5 style="text-align:center; color:red ; font-size: 20px;">  🟢 Clip 🟢 </h5>
<p style="text-align:center; font-size: 20px;">
🔸برای نگه داشتن مقادیر یک آرایه در یک محدوده استفاده می شود🔸
</p>

In [48]:
arr = np.array([0,1,-3,-4,5,6,7,2,3])

In [49]:
arr.clip(1,5)

array([1, 1, 1, 1, 5, 5, 5, 2, 3])

In [50]:
arr.clip(2,3)

array([2, 2, 2, 2, 3, 3, 3, 2, 3])

In [51]:
arr.clip(3,5)

array([3, 3, 3, 3, 5, 5, 5, 3, 3])

<hr>
<h5 style="text-align:center; color:red ; font-size: 20px;">  🟢 Sort 🟢 </h5>
<p style="text-align:center; font-size: 20px;">
🔸آرایه ها را مرتب می کند🔸
</p>

<div style="text-align:left; font-size: 20px;">

np.sort(arr , kind)

kind: Sorting algorithm to use. {‘quicksort’, ‘mergesort’, ‘heapsort’, ‘stable’}






</div>

In [56]:
arr = np.array([2,3,1,7,4,5])
arr = np.sort(arr , kind='heapsort')
arr

array([1, 2, 3, 4, 5, 7])

<hr>
<div style="text-align:center;"  >
<a href='https://chistio.ir/%D8%A7%D9%86%D9%88%D8%A7%D8%B9-%D9%85%D8%A7%D8%AA%D8%B1%DB%8C%D8%B3-%D9%88%DB%8C%DA%98%DA%AF%DB%8C%D9%87%D8%A7%DB%8C-%D9%85%D8%AE%D8%AA%D9%84%D9%81-%D8%A2%D9%86-%D9%87%D8%A7/'> آموزش انواع ماتریس استاد کاویانی </a>

<a href='https://levelup.gitconnected.com/50-numpy-functions-you-really-needed-for-data-science-fa09e8eb0cf0'> source </a>
</div>




<div style=" padding: 40px; text-align: center; color: #8e44ad;text-shadow: 2px 2px 0px #f1c40f; ">
    <h1 style="font-family: 'Roboto', sans-serif;ext-align: center;  font-size: 72px; margin-top: 0; margin-bottom: 20px;">
    Exercise 3
    </h1>
</div>

![ex2](ex2.png)

<hr>
<h5 style="text-align:center; color:red ; font-size: 20px;">  🟢 Quick Sort 🟢 </h5>
<p style="text-align:right; font-size: 20px;">
 یک الگوریتم مرتب‌سازی بازگشتی است که از روش تقسیم و حل استفاده می‌کند. الگوریتم به گونه‌ای طراحی شده است که با استفاده از تابع پایوت، آرایه را به دو بخش تقسیم می‌کند: عناصری که از مقدار پایوت کوچکتر هستند و عناصری هستند که بزرگتر یا مساوی پایوت هستند. سپس هر بخش را به صورت بازگشتی مرتب می کند
</p>



![quick](sort1.png)

In [57]:
not_sorted = np.array([6,6,2,4,5,1,0,10,9,14,25])
np.sort(not_sorted , kind='quicksort')


array([ 0,  1,  2,  4,  5,  6,  6,  9, 10, 14, 25])

<hr>
<h5 style="text-align:center; color:red ; font-size: 20px;">  🟢 Heap Sort 🟢 </h5>
<p style="text-align:right; font-size: 20px;">
الگوریتم هیپ به این صورت عمل می‌کند که ابتدا یک هیپ ساخته شده و سپس با حذف ریشه و برگرداندن آن به مکان مناسب خود در هیپ عناصر را به ترتیب مرتب می‌کند
</p>



![heap](heap1.png)

![heap](heap2.png)

![heap](heap3.png)

![heap](heap4.png)

![heap](heap5.png)

![heap](heap7.png)

In [58]:
not_sorted = np.array([6,6,2,4,5,1,0,10,9,14,25])
np.sort(not_sorted , kind='heapsort')

array([ 0,  1,  2,  4,  5,  6,  6,  9, 10, 14, 25])

<hr>
<h5 style="text-align:center; color:red ; font-size: 20px;">  🟢 Merge Sort 🟢 </h5>






![merge](MergeSort.png)

In [59]:
not_sorted = np.array([6,6,2,4,5,1,0,10,9,14,25])
np.sort(not_sorted , kind='mergesort')

array([ 0,  1,  2,  4,  5,  6,  6,  9, 10, 14, 25])